# Uygulama adı (Fly.io üzerinde benzersiz olmalı)
app = "frame-customizer-v2"

# Bu kısmı silebilirsin, çünkü Dockerfile kullanıyoruz
# [build]

[env]
  NODE_ENV = "production"
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0